[OnnxRuntime]
git-tree-sha1 = "e200d3ceaab42d75a2aad3a399bacaab8eb7621d"

    [[OnnxRuntime.download]]
    url = "https://github.com/IanET/LibOnnxRuntimeGenerator/raw/refs/heads/v1.23.2/microsoft.ml.onnxruntime.tar.gz"
    sha256 = "a51fdce3946a8d49d44403cb8603c638e144a552b4579ae15b1e9a6291dba1cc"